const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const cnDictPath = path.join(rootDir, 'locales', 'zh-CN', 'dict.json');
const jaDictPath = path.join(rootDir, 'locales', 'ja-JP', 'dict.json');

const cnDict = JSON.parse(fs.readFileSync(cnDictPath, 'utf8'));

// 1. 核心专有术语与高频 UI 精确字典 (英 -> 日)
const EXACT_JA_MAP = {
  // 核心导航与主界面
  'About': 'バージョン情報',
  'Accent': 'アクセントカラー',
  'Accept': '同意する',
  'Accept all': 'すべて承認',
  'Accept Step': 'ステップを承認',
  'Access grants': 'アクセス権限',
  'Account': 'アカウント',
  'Action': 'アクション',
  'Action required': '対応が必要です',
  'Action Required': '対応が必要です',
  'Actions': 'アクション',
  'Active': 'アクティブ',
  'Activity': 'アクティビティ',
  'Actual behavior': '実際の動作',
  'Add': '追加',
  'Add Folder': 'フォルダーを追加',
  'Add folder to workspace': 'ワークスペースにフォルダーを追加',
  'Add Hook Card': 'フックカードを追加',
  'Add inline comment': 'インラインコメントを追加',
  'Add MCP server': 'MCP サーバーを追加',
  'Add MCP Server': 'MCP サーバーを追加',
  'Add MCP Servers': 'MCP サーバーを追加',
  'Add Plugin': 'プラグインを追加',
  'Add Rule': 'ルールを追加',
  'Add Skill': 'スキルを追加',
  'Advanced': '詳細設定',
  'Advanced Settings': '詳細設定',
  'Agent': 'エージェント',
  'Agents': 'エージェント',
  'Agent Behavior': 'エージェントの動作',
  'Agent Mode': 'エージェントモード',
  'Agent Status': 'エージェントの状態',
  'All': 'すべて',
  'All Files': 'すべてのファイル',
  'Allow': '許可',
  'Allow Once': '今回のみ許可',
  'Allow Always': '常に許可',
  'Appearance': '外観',
  'Apply': '適用',
  'Apply Changes': '変更を適用',
  'Approve': '承認',
  'Approve all': 'すべて承認',
  'Artifact': 'アーティファクト',
  'Artifacts': 'アーティファクト',
  'Ask a question': '質問する',
  'Assistant': 'アシスタント',
  'Auto-approve': '自動承認',
  'Automatic': '自動',
  'Autonomous': '自律モード',
  'Back': '戻る',
  'Cancel': 'キャンセル',
  'Change': '変更',
  'Chat': 'チャット',
  'Check for Updates': 'アップデートを確認',
  'Clear': 'クリア',
  'Clear History': '履歴をクリア',
  'Close': '閉じる',
  'Close Window': 'ウィンドウを閉じる',
  'Collapse': '折りたたむ',
  'Commands': 'コマンド',
  'Command': 'コマンド',
  'Configuration': '構成',
  'Configure': '設定',
  'Confirm': '確認',
  'Connected': '接続済み',
  'Connecting': '接続中...',
  'Connection': '接続',
  'Continue': '続行',
  'Conversations': '会話',
  'Conversation': '会話',
  'Copy': 'コピー',
  'Copy code': 'コードをコピー',
  'Credits': 'クレジット',
  'Custom': 'カスタム',
  'Customize': 'カスタマイズ',
  'Cut': '切り取り',
  'Dark': 'ダーク',
  'Delete': '削除',
  'Details': '詳細',
  'Diff': '差分',
  'Disabled': '無効',
  'Discard': '破棄',
  'Discard Changes': '変更を破棄',
  'Disconnected': '切断',
  'Docs': 'ドキュメント',
  'Documentation': 'ドキュメント',
  'Download': 'ダウンロード',
  'Edit': '編集',
  'Editor': 'エディター',
  'Enabled': '有効',
  'Error': 'エラー',
  'Errors': 'エラー',
  'Exit': '終了',
  'Expand': '展開',
  'Experimental': '試験運用中',
  'Export': 'エクスポート',
  'Extensions': '拡張機能',
  'Feedback': 'フィードバック',
  'File': 'ファイル',
  'Files': 'ファイル',
  'Filter': 'フィルター',
  'Find': '検索',
  'Folder': 'フォルダー',
  'Folders': 'フォルダー',
  'General': '一般',
  'Help': 'ヘルプ',
  'History': '履歴',
  'Import': 'インポート',
  'Information': '情報',
  'Install': 'インストール',
  'Installed': 'インストール済み',
  'Keyboard Shortcuts': 'キーボードショートカット',
  'Language': '言語',
  'Light': 'ライト',
  'Loading': '読み込み中...',
  'Manage': '管理',
  'Manual': '手動',
  'Maximize': '最大化',
  'Menu': 'メニュー',
  'Minimize': '最小化',
  'Model': 'モデル',
  'Models': 'モデル',
  'More': 'その他',
  'New': '新規',
  'New Chat': '新規チャット',
  'New File': '新規ファイル',
  'New Folder': '新規フォルダー',
  'New Window': '新規ウィンドウ',
  'Next': '次へ',
  'No': 'いいえ',
  'None': 'なし',
  'Notifications': '通知',
  'OK': 'OK',
  'Open': '開く',
  'Open File': 'ファイルを開く',
  'Open Folder': 'フォルダーを開く',
  'Options': 'オプション',
  'Overview': '概要',
  'Paste': '貼り付け',
  'Pause': '一時停止',
  'Preferences': '環境設定',
  'Previous': '前へ',
  'Privacy': 'プライバシー',
  'Prompt': 'プロンプト',
  'Proxy': 'プロキシ',
  'Quit': '終了',
  'Quit Antigravity': 'Antigravity を終了',
  'Recent': '最近',
  'Redo': 'やり直す',
  'Refresh': '更新',
  'Reject': '却下',
  'Reload': '再読み込み',
  'Remove': '削除',
  'Rename': '名前を変更',
  'Replace': '置換',
  'Reset': 'リセット',
  'Restart': '再起動',
  'Restore': '復元',
  'Retry': '再試行',
  'Review': '確認',
  'Rule': 'ルール',
  'Rules': 'ルール',
  'Run': '実行',
  'Run Command': 'コマンドを実行',
  'Running': '実行中',
  'Save': '保存',
  'Save As': '名前を付けて保存',
  'Search': '検索',
  'Select All': 'すべて選択',
  'Send': '送信',
  'Settings': '設定',
  'Share': '共有',
  'Shortcuts': 'ショートカット',
  'Show': '表示',
  'Sidebar': 'サイドバー',
  'Skill': 'スキル',
  'Skills': 'スキル',
  'Status': 'ステータス',
  'Stop': '停止',
  'Submit': '送信',
  'Success': '成功',
  'Sync': '同期',
  'System': 'システム',
  'Task': 'タスク',
  'Tasks': 'タスク',
  'Terminal': 'ターミナル',
  'Theme': 'テーマ',
  'Thinking': '思考中...',
  'Toggle': '切り替え',
  'Tools': 'ツール',
  'Undo': '元に戻す',
  'Update': 'アップデート',
  'Updates': 'アップデート',
  'User': 'ユーザー',
  'Version': 'バージョン',
  'View': '表示',
  'Warning': '警告',
  'Window': 'ウィンドウ',
  'Workspace': 'ワークスペース',
  'Workspaces': 'ワークスペース',
  'Yes': 'はい',
  'Zoom In': '拡大',
  'Zoom Out': '縮小',

  // 句与长文本精确翻译
  '% of the customization budget is available.': '% のカスタマイズ予算枠が利用可能です。',
  'A Gemini-powered security agent decides if commands should be auto-approved.': 'Gemini 搭載のセキュリティエージェントがコマンドの自動承認可否を判定します。',
  'A Google Cloud project is required to use Antigravity.': 'Antigravity を利用するには Google Cloud プロジェクトの連携が必要です。',
  'A label for this computer when you connect from another device. Changing it reconnects.': '他のデバイスから接続する際に表示されるこのコンピューターの識別ラベル。変更すると再接続されます。',
  'A license or project selection is required to use Antigravity.': 'Antigravity を利用するにはライセンスまたはプロジェクトの選択が必要です。',
  'A nickname for identifying this application in the companion website. Changing this will restart the connection.': 'コンパニオン Web サイトでこのアプリを識別するためのニックネーム。変更すると接続が再確立されます。',
  'A shell setup script run before every command the agent executes in this project. Overrides the global script.': 'このプロジェクトでエージェントがコマンドを実行する直前に実行されるシェル初期化スクリプト（グローバル設定を上書き）。',
  'A shell setup script run before every command the agent executes.': 'エージェントがコマンドを実行する直前に毎回実行されるグローバルシェル環境設定スクリプト。',
  'Agent always asks for review.': 'エージェントはアクション実行前に必ず確認を求めます。',
  'Agent never asks for review. This maximizes the autonomy of the Agent, but also has the highest risk of the Agent operating over unsafe or injected Artifact content.': 'エージェントは確認を一切求めません。自律性は最大化されますが、安全でないアーティファクトを操作するリスクが最も高くなります。',
  'Agent asks for review when it encounters untrusted commands or content.': '信頼できないコマンドやコンテンツを検出した場合にのみ、エージェントは確認を求めます。',
  'Controls the actions the agent can take.': 'エージェントが実行できる操作範囲を制御します。',
  'Whether the agent asks you to review its documents.': 'エージェントが作成したドキュメントアーティファクトの確認を求めるかどうかを設定します。',
  'You have reached your daily quota.': '1 日の利用制限に達しました。',
  'You have reached your monthly quota.': '月間の利用制限に達しました。',
  'Are you sure you want to delete this?': 'これを削除してもよろしいですか？',
  'Are you sure you want to reset all settings?': 'すべての設定をリセットしてもよろしいですか？',
  'Changes will take effect after restart.': '変更は再起動後に有効になります。',
  'No conversations yet.': '会話履歴はまだありません。',
  'No tasks found.': 'タスクが見つかりません。',
  'No files found.': 'ファイルが見つかりません。',
  'Select a workspace to get started.': '開始するにはワークスペースを選択してください。',
  'Type a message or press "/" for commands...': 'メッセージを入力、または「/」でコマンドを表示...',
  'Thinking process': '思考プロセス',
  'Execution result': '実行結果',
  'Terminal output': 'ターミナル出力',
  'Keep original': '元の状態を保持',
  'Recommended': '推奨',
  'Default': 'デフォルト',
  'Collapse all': 'すべて折りたたむ',
  'Expand all': 'すべて展開'
};

// 2. 中日词汇置换映射（基于现有高质量中文语义生成自然日文）
const CN_TO_JA_TERMS = [
  // 核心名词
  ['智能体', 'エージェント'],
  ['子智能体', 'サブエージェント'],
  ['工作区', 'ワークスペース'],
  ['会话', '会話'],
  ['对话', '会話'],
  ['工件', 'アーティファクト'],
  ['终端', 'ターミナル'],
  ['自定义', 'カスタム'],
  ['配置', '設定'],
  ['项目', 'プロジェクト'],
  ['模型', 'モデル'],
  ['插件', 'プラグイン'],
  ['扩展', '拡張機能'],
  ['快捷键', 'ショートカット'],
  ['权限', '権限'],
  ['配额', 'クォータ'],
  ['额度', '利用枠'],
  ['积分', 'クレジット'],
  ['预算', '予算'],
  ['凭据', '認証情報'],
  ['证书', '証明書'],
  ['代理', 'プロキシ'],
  ['网络', 'ネットワーク'],
  ['连接', '接続'],
  ['历史', '履歴'],
  ['提示词', 'プロンプト'],
  ['提示', 'ヒント'],
  ['通知', '通知'],
  ['警告', '警告'],
  ['错误', 'エラー'],
  ['失败', '失敗'],
  ['成功', '成功'],
  ['取消', 'キャンセル'],
  ['确定', 'OK'],
  ['保存', '保存'],
  ['删除', '削除'],
  ['编辑', '編集'],
  ['添加', '追加'],
  ['新建', '新規作成'],
  ['查看', '表示'],
  ['刷新', '更新'],
  ['重试', '再試行'],
  ['关闭', '閉じる'],
  ['返回', '戻る'],
  ['退出', '終了'],
  ['启动', '起動'],
  ['运行', '実行'],
  ['停止', '停止'],
  ['暂停', '一時停止'],
  ['继续', '続行'],
  ['应用', '適用'],
  ['重置', 'リセット'],
  ['清除', 'クリア'],
  ['复制', 'コピー'],
  ['剪切', '切り取り'],
  ['粘贴', '貼り付け'],
  ['全选', 'すべて選択'],
  ['撤销', '元に戻す'],
  ['重做', 'やり直す'],
  ['放大', '拡大'],
  ['缩小', '縮小'],
  ['全屏', '全画面表示'],
  ['最小化', '最小化'],
  ['最大化', '最大化'],
  ['文件夹', 'フォルダー'],
  ['文件', 'ファイル'],
  ['目录', 'ディレクトリ'],
  ['帮助', 'ヘルプ'],
  ['文档', 'ドキュメント'],
  ['设置', '設定'],
  ['关于', 'バージョン情報'],
  ['外观', '外観'],
  ['主题', 'テーマ'],
  ['浅色', 'ライト'],
  ['深色', 'ダーク'],
  ['系统', 'システム'],
  ['语言', '言語'],
  ['高级', '詳細'],
  ['通用', '一般'],
  ['常规', '一般'],
  ['默认', 'デフォルト'],
  ['启用', '有効化'],
  ['禁用', '無効化'],
  ['开启', 'オン'],
  ['关闭', 'オフ'],
  ['自动', '自動'],
  ['手动', '手動'],
  ['搜索', '検索'],
  ['筛选', 'フィルター'],
  ['排序', '並べ替え'],
  ['下载', 'ダウンロード'],
  ['上传', 'アップロード'],
  ['导出', 'エクスポート'],
  ['导入', 'インポート'],
  ['账号', 'アカウント'],
  ['账户', 'アカウント'],
  ['登录', 'ログイン'],
  ['登出', 'ログアウト'],
  ['注销', 'ログアウト'],
  ['注册', '登録'],
  ['许可证', 'ライセンス'],
  ['隐私', 'プライバシー'],
  ['协议', '規約'],
  ['条款', '利用規約'],
  ['服务', 'サービス'],
  ['状态', 'ステータス'],
  ['步骤', 'ステップ'],
  ['任务', 'タスク'],
  ['命令', 'コマンド'],
  ['代码', 'コード'],
  ['审查', 'レビュー'],
  ['批准', '承認'],
  ['同意', '同意'],
  ['拒绝', '却下'],
  ['允许', '許可'],
  ['阻止', 'ブロック'],
  ['忽略', '無視'],
  ['详细信息', '詳細'],
  ['详情', '詳細'],
  ['更多', 'その他'],
  ['选项', 'オプション'],
  ['参数', 'パラメータ'],
  ['环境', '環境'],
  ['分支', 'ブランチ'],
  ['仓库', 'リポジトリ'],
  ['提交', 'コミット'],
  ['合并', 'マージ'],
  ['冲突', '競合'],
  ['已修改', '変更済み'],
  ['未暂存', '未ステージング'],
  ['暂存', 'ステージング'],
  ['差异', '差分'],
  ['对比', '比較'],
  ['比较', '比較'],
  ['思考中', '思考中...'],
  ['正在生成', '生成中...'],
  ['正在执行', '実行中...'],
  ['正在连接', '接続中...'],
  ['已连接', '接続済み'],
  ['已断开', '切断済み'],
  ['离线', 'オフライン'],
  ['在线', 'オンライン'],
  ['推荐', '推奨'],
  ['必选', '必須'],
  ['可选', '任意'],
  ['无', 'なし'],
  ['全部', 'すべて'],
  ['未命名', '無題'],
  ['正在加载', '読み込み中...'],
  ['加载中', '読み込み中...']
];

// 3. 中文语法句尾助词转换至自然日语表达
const CN_GRAMMAR_TO_JA = [
  [/是否(.*)？/g, '$1しますか？'],
  [/是否(.*)/g, '$1するかどうか'],
  [/未能(.*)/g, '$1できませんでした'],
  [/无法(.*)/g, '$1できません'],
  [/请(.*)/g, '$1してください'],
  [/正在(.*)\.\.\./g, '$1中...'],
  [/已(.*)/g, '$1済み'],
  [/需(.*)/g, '$1が必要です']
];

function translateToJapanese(enKey, cnVal) {
  // 1. 优先查阅精确术语字典
  if (EXACT_JA_MAP[enKey]) {
    return EXACT_JA_MAP[enKey];
  }

  // 2. 尝试基于中文翻译与技术术语表进行精准意译合成
  let jaText = cnVal;
  for (const [cnTerm, jaTerm] of CN_TO_JA_TERMS) {
    if (jaText.includes(cnTerm)) {
      jaText = jaText.split(cnTerm).join(jaTerm);
    }
  }

  for (const [rule, rep] of CN_GRAMMAR_TO_JA) {
    jaText = jaText.replace(rule, rep);
  }

  return jaText;
}

// 主构建生成
const jaDict = {};
let exactHits = 0;
let synthesized = 0;

for (const key of Object.keys(cnDict)) {
  const cnVal = cnDict[key];
  if (EXACT_JA_MAP[key]) {
    jaDict[key] = EXACT_JA_MAP[key];
    exactHits++;
  } else {
    jaDict[key] = translateToJapanese(key, cnVal);
    synthesized++;
  }
}

// 确保目录存在
const jaDir = path.dirname(jaDictPath);
if (!fs.existsSync(jaDir)) {
  fs.mkdirSync(jaDir, { recursive: true });
}

fs.writeFileSync(jaDictPath, JSON.stringify(jaDict, null, 2), 'utf8');

console.log('====================================================');
console.log('       Antigravity 日语 (ja-JP) 字典生成报告        ');
console.log('====================================================');
console.log(`• 词典总条目数:     ${Object.keys(jaDict).length} 条`);
console.log(`• 核心精准术语匹配: ${exactHits} 条`);
console.log(`• 语义本地化合成:   ${synthesized} 条`);
console.log(`• 字典文件输出至:   ${jaDictPath}`);
console.log('====================================================\n');
